/*
    Generated by OpenAI's ChatGPT on 2026-04-29.
    This code demonstrates how to use LD_PRELOAD to intercept SSL_write calls and inject a custom header into HTTP requests.
*/

#define _GNU_SOURCE
#include <dlfcn.h>
#include <string.h>
#include <stdlib.h>
#include <openssl/ssl.h>

typedef int (*ssl_write_func)(SSL *ssl, const void *buf, int num);

int SSL_write(SSL *ssl, const void *buf, int num)
{
    fprintf(stderr, "[HOOK] SSL_write called, len=%d\n", num);
    static ssl_write_func real_SSL_write = NULL;

    if (!real_SSL_write) {
        real_SSL_write = (ssl_write_func)dlsym(RTLD_NEXT, "SSL_write");
    }

    const char *data = (const char *)buf;

    // 只示範 HTTP/1.1 header injection
    if (num > 0 && strstr(data, "\r\n\r\n")) {
        const char *inject = "X-NF-Signature: test-signature\r\n";

        char *new_buf = malloc(num + strlen(inject) + 1);
        if (!new_buf) {
            return real_SSL_write(ssl, buf, num);
        }

        char *header_end = strstr(data, "\r\n\r\n");
        int header_len = header_end - data + 2;

        memcpy(new_buf, data, header_len);
        memcpy(new_buf + header_len, inject, strlen(inject));
        memcpy(new_buf + header_len + strlen(inject),
               data + header_len,
               num - header_len);

        int new_len = num + strlen(inject);

        int ret = real_SSL_write(ssl, new_buf, new_len);
        free(new_buf);
        return ret;
    }

    return real_SSL_write(ssl, buf, num);
}