// nrf_read_loader.c
// Loads nrf_read.bpf.o, attaches a uretprobe to net/http.readRequest
// in the target NRF process, and prints header events from the ring buffer.
//
// Build:  see Makefile
// Run:    sudo ./nrf_read_loader <pid> <path/to/nrf>
// Quick:  sudo ./nrf_read_loader $(pgrep nrf) $(realpath /proc/$(pgrep nrf)/exe)

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <errno.h>
#include <signal.h>
#include <sys/resource.h>
#include <bpf/libbpf.h>

#include "nrf_read.skel.h"          // generated by: bpftool gen skeleton nrf_read.bpf.o

// Must mirror the BPF-side struct exactly
struct header_event {
    uint32_t pid;
    char     method[16];
    char     path[128];
    char     hdr_key[64];
    char     hdr_val[128];
};

static volatile bool g_stop = false;

static void on_signal(int sig) { (void)sig; g_stop = true; }

// ── ring buffer callback ──────────────────────────────────────────────────────

static int on_event(void *ctx, void *data, size_t sz)
{
    (void)ctx;
    if (sz < sizeof(struct header_event))
        return 0;

    const struct header_event *ev = data;

    printf("pid=%-6u  %-7s %-45s  %s: %s\n",
           ev->pid,
           ev->method[0]  ? ev->method  : "(empty)",
           ev->path[0]    ? ev->path    : "/",
           ev->hdr_key[0] ? ev->hdr_key : "(no key)",
           ev->hdr_val[0] ? ev->hdr_val : "(no val)");
    fflush(stdout);
    return 0;
}

// ── suppress libbpf debug noise; keep warnings and errors ────────────────────

static int libbpf_log(enum libbpf_print_level level,
                      const char *fmt, va_list ap)
{
    if (level == LIBBPF_DEBUG) return 0;
    return vfprintf(stderr, fmt, ap);
}

// ── main ─────────────────────────────────────────────────────────────────────

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr,
            "Usage: %s <pid> <nrf_binary>\n"
            "\n"
            "  pid        — PID of the running free5GC NRF process\n"
            "  nrf_binary — path to the NRF ELF (must have DWARF/symtab)\n"
            "\n"
            "Example:\n"
            "  sudo %s $(pgrep nrf) $(realpath /proc/$(pgrep nrf)/exe)\n",
            argv[0], argv[0]);
        return 1;
    }

    int         target_pid = atoi(argv[1]);
    const char *exe_path   = argv[2];

    if (target_pid <= 0) {
        fprintf(stderr, "Invalid pid: %s\n", argv[1]);
        return 1;
    }

    // ── pre-flight: confirm the symbol exists ─────────────────────────────────
    // If it's missing the binary was built with -trimpath + stripped symbols
    // or the function was inlined.  Fix: go build -gcflags=all=-l ./cmd/nrf
    printf("[*] Checking ELF symbol table in %s …\n", exe_path);
    {
        char cmd[512];
        snprintf(cmd, sizeof(cmd),
                 "go tool nm %s 2>/dev/null | grep -q 'net/http.readRequest'"
                 " && echo '    found: net/http.readRequest'"
                 " || echo '    MISSING — rebuild NRF with: go build -gcflags=all=-l'",
                 exe_path);
        system(cmd);
    }

    // ── raise memlock rlimit ──────────────────────────────────────────────────
    struct rlimit rl = { RLIM_INFINITY, RLIM_INFINITY };
    if (setrlimit(RLIMIT_MEMLOCK, &rl))
        perror("setrlimit (non-fatal on newer kernels)");

    signal(SIGINT,  on_signal);
    signal(SIGTERM, on_signal);

    libbpf_set_print(libbpf_log);

    // ── open skeleton ─────────────────────────────────────────────────────────
    struct nrf_read_bpf *skel = nrf_read_bpf__open();
    if (!skel) {
        fprintf(stderr, "nrf_read_bpf__open failed\n");
        return 1;
    }

    // Inject the target pid into the BPF read-only data section.
    // The BPF program uses this to drop events from unrelated processes.
    skel->rodata->g_target_pid = (uint32_t)target_pid;

    // ── load (JIT-compile + verify) ───────────────────────────────────────────
    if (nrf_read_bpf__load(skel)) {
        fprintf(stderr, "nrf_read_bpf__load failed — check dmesg for verifier log\n");
        nrf_read_bpf__destroy(skel);
        return 1;
    }

    // ── attach uretprobe ──────────────────────────────────────────────────────
    // retprobe=true → fires on function return, giving us the *Request value.
    // pid=target_pid → kernel only installs the breakpoint in that process's
    //                  address space (less overhead than pid=-1 + BPF filter).
    LIBBPF_OPTS(bpf_uprobe_opts, uprobe_opts,
        .func_name = "net/http.readRequest",
        .retprobe  = true,
    );

    struct bpf_link *link = bpf_program__attach_uprobe_opts(
        skel->progs.probe_readrequest,
        target_pid,
        exe_path,
        0,              // offset=0 — libbpf resolves via func_name
        &uprobe_opts);

    if (!link) {
        fprintf(stderr,
            "attach_uprobe_opts failed: %s\n"
            "\n"
            "Common causes:\n"
            "  1. Symbol stripped — rebuild: go build -gcflags=all=-l ./cmd/nrf\n"
            "  2. Binary was inlined — same fix as above\n"
            "  3. Wrong exe_path — use the real path, not a symlink wrapper\n"
            "  4. Missing CAP_SYS_ADMIN — run with sudo\n"
            "  5. Kernel < 4.17 — upgrade (uprobe needs perf_event_open)\n",
            strerror(errno));
        nrf_read_bpf__destroy(skel);
        return 1;
    }

    printf("[*] Attached uretprobe → net/http.readRequest (pid %d)\n", target_pid);
    printf("[*] Waiting for NRF requests …  (Ctrl-C to stop)\n\n");
    printf("%-10s  %-7s  %-45s  %s\n",
           "PID", "METHOD", "PATH", "HEADER: VALUE");
    printf("%-10s  %-7s  %-45s  %s\n",
           "----------", "-------",
           "---------------------------------------------",
           "---------------------------------------------");

    // ── ring buffer poll loop ─────────────────────────────────────────────────
    struct ring_buffer *rb = ring_buffer__new(
        bpf_map__fd(skel->maps.events), on_event, NULL, NULL);
    if (!rb) {
        fprintf(stderr, "ring_buffer__new: %s\n", strerror(errno));
        bpf_link__destroy(link);
        nrf_read_bpf__destroy(skel);
        return 1;
    }

    while (!g_stop) {
        int ret = ring_buffer__poll(rb, 200 /* ms timeout */);
        if (ret < 0 && errno != EINTR) {
            fprintf(stderr, "ring_buffer__poll: %s\n", strerror(errno));
            break;
        }
    }

    printf("\n[*] Detaching…\n");
    ring_buffer__free(rb);
    bpf_link__destroy(link);
    nrf_read_bpf__destroy(skel);
    return 0;
}